# Configuration file for Sentiment Analysis AI Model

# Data paths
data:
  raw_data_path: "data/raw/reviews.csv"
  processed_data_path: "data/processed/"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  random_seed: 42

# Model parameters
model:
  type: "naive_bayes"  # Options: naive_bayes, logistic_regression, svm
  max_features: 5000
  ngram_range: [1, 2]  # Use unigrams and bigrams
  min_df: 2
  max_df: 0.95

# Training parameters
training:
  save_model_path: "models/sentiment_model.pkl"
  save_vectorizer_path: "models/vectorizer.pkl"
  save_metrics_path: "models/metrics.json"

# Preprocessing
preprocessing:
  lowercase: true
  remove_stopwords: true
  remove_punctuation: true
  remove_numbers: false
  lemmatize: true

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
